### ISSUE TITLE
Fahrschein does not commit empty batches to high-level API

### ISSUE THREAD

**Issue by alnkpa** [zalando-incubator/fahrschein#119] opened 2016-12-05 10:44 UTC
When using the `ManagedCursorManager`, commiting can fail with

```
[org.zalando.fahrschein.ManagedCursorManager] Unexpected status code [422] for subscription [ce41ac5c-1c1d-42be-a5db-32f1f976a91b] to event [event] in partition [0] with offset [90458]
```

Nakadi rquires that

> The client must commit at least once every 60 seconds, otherwise Nakadi will consider the client to be gone and will close the connection.

The error above appears if Nakadi closed the stream without the fahrschein-client noticing.

This can be mitigated by commiting even empty batches to the Nakadi high-level API.

**Comment by jhorstmann** [comment] 2016-12-05 11:59
> Unexpected status code [422]

This can only occur if you haven't registered the `ProblemHandlingClientHttpRequestFactory`, this would check the status code before and throw an `IOProblem`.

**Comment by jhorstmann** [comment] 2016-12-05 12:06
@lukasniemeier-zalando @alnkpa What would you think about removing the `ProblemHandlingClientHttpRequestFactory` and instead handling status codes explicitly in the client?

**Comment by jhorstmann** [comment] 2016-12-06 14:06
Closing as not a bug, but I'll think about making the problem handling easier to use

**Closed by jhorstmann** 2016-12-06 14:06 UTC
Labels: invalid
