### ISSUE TITLE
Typo in metadata field occurredAt

### ISSUE THREAD

**Issue by Markinhos** [zalando-incubator/fahrschein#145] opened 2017-03-02 13:43 UTC
There is a typo in the field `occurredAt` in Metadata class, which prevents to deserialize that property. 

The current name is `occuredAt` while it should be `occurredAt`

**Comment by jhorstmann** [comment] 2017-03-02 16:05
Duplicate of #138, but thanks for the reminder to release a new version

**Comment by jhorstmann** [comment] 2017-03-02 16:14
Released [0.8.1](https://github.com/zalando-incubator/fahrschein/releases/tag/0.8.1)

**Closed by jhorstmann** 2017-03-02 16:14 UTC
